### ISSUE TITLE
Deployment with several flavours

### ISSUE THREAD

**Issue by frmadem** [prefapp/action-deployment-dispatch#16]
The actual deployment system let us to:

1. Define a specif flavour, with a particular Dockerfile and build-args and trigger it with an event. 
2. Define a tenant-app-env for deployment in one or several services names
3. Select a flavour to deploy. 

Therefore:

```yaml
# build-images.yaml
foo:
  triggers:
    push:
      branches: ["master"]
    build_args:
      arg:  "value 1"
      arg2: "value 2"
   dockerfile: Dockerfile.foo


```

**Comment by alambike** [comment]
I think you miss one more step in the chain, it should be:
`tenant`-`app`-`env`-`slot`

Thus, the development team could be able to deploy each flavor in its slot

```yaml
foo:
  app:
    dev:
      default:
        service_names:
          - service1
        version: branch_master
        flavour: foo
      tenant2:
        service_names:
          - service2
        version: branch_master
        flavour: foo2
```


Also, the development team should define both flavors in the build-image.yaml:
```yaml
foo:
  triggers:
    push:
      branches: ["master"]
    build_args:
      arg:  "value 1"
      arg2: "value 2"
   dockerfile: Dockerfile.foo
foo2:
  triggers:
    push:
      branches: ["master"]
    build_args:
      arg:  "value 3"
      arg2: "value 4"
   dockerfile: Dockerfile.foo
```

**Comment by alambike** [comment]
After conversation we see the need to alter the definition of a deployment to allow specify a list of deployments in the same tenant-app-environment-slot, that we want to update with a flavour, ie:

```yaml
foo:
  app:
    dev:
      default:
        - name: service1
          service_names:
            - service1
          version: branch_master
          flavour: foo
        - name: service2
          service_names:
            - service2
          version: branch_master
          flavour: foo2
```
@frmadem in order to generate the v3 of the action, I would go for adding support for the slots coordinate, in addition to the support to be able to modify multiple services in the same slot (<tenant>-<app>-<env >-<slot>) with different flavors.
 
Another option that I see as less interesting would be to try to get a version v2.1 compatible with both formats of the deployments file, without slots (postponed for a future v3) but with support for a list or a map of service values to modify their image.
