### ISSUE TITLE
Add new input to specify event_type

### ISSUE THREAD

**Issue by jalvarezit** [prefapp/action-deployment-dispatch#44]
# Descripción

Para permitir una actualización más cómoda del workflow es importante permitir especificar el `event_type` de manera que se puede crear otro workflow en el repo de estado con un `event_type` y únicamente llamar a ese desde la versión actualizada, quedaría de la siguiente manera:

```
      - name: Dispatch changes
        uses: prefapp/action-deployment-dispatch@v4
        with:
          event_type: new-dispatch-image
          state_repo: ${{ matrix.dispatches.state_repo }}
          image_repository: ${{ matrix.dispatches.image_repository }}
          token: ${{ secrets.REPO_STATE_TOKEN }}
          base_folder: "apps"
```
